=== AvatarWorld/muspy/muspy/io/schemas/music.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "MusPy JSON schema v0.0",
    "description": "A simple, intuitive format for symbolic music",
    "type": "object",
    "properties": {
        "meta": {
            "description": "Meta data",
            "type": "object",
            "properties": {
                "version": {
                    "description": "Schema version",
                    "type": "string",
                    "pattern": "[0-9].[0-9]"
                },
                "song": {
                    "description": "Song information",
                    "type": "object",
                    "properties": {
                        "title": {
                            "description": "Song title",
                            "type": ["string", "null"]
                        },
                        "artist": {
                            "description": "Main artist of the song",
                            "type": ["string", "null"]
                        },
                        "composers": {
                            "description": "Composers of the song",
                            "type": ["array", "null"],
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "source": {
                    "description": "Source information",
                    "type": "object",
                    "properties": {
                        "filename": {
                            "description": "Path to the file in the collection",
                            "type": ["string", "null"]
                        },
                        "collection": {
                            "description": "Name of the collection",
                            "type": ["string", "null"]
                        },
                        "format": {
                            "description": "Format of the source file {midi, musicxml, abc, null}",
                            "type": ["string", "null"]
                        },
                        "id": {
                            "description": "Unique ID of the file",
                            "type": ["string", "null"]
                        }
                    }
                }
            }
        },
        "timing": {
            "description": "Timing system",
            "type": "object",
            "properties": {
                "is_symbolic_timing": {
                    "description": "If true, the timing is in time steps. Otherwise, it's in seconds.",
                    "type": "boolean"
                },
                "beat_resolution": {
                    "description": "Time steps per beat (only effective when `is_symbolic_timing` is true)",
                    "type": ["integer", "null"]
                }
            }
        },
        "time_signatures": {
            "description": "Time signatures",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "time": {
                        "description": "Event time",
                        "type": "number"
                    },
                    "numerator": {
                        "description": "Numerator of time signature",
                        "type": "integer"
                    },
                    "denominator": {
                        "description": "Denominator of time signature",
                        "type": "integer"
                    }
                }
            }
        },
        "key_signatures": {
            "description": "Key signatures",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "time": {
                        "description": "Event time",
                        "type": "number"
                    },
                    "root": {
                        "description": "Root: {C, C#, Db, D, D#, Eb, E, F, F#, Gb, G, G#, Ab, A, A#, Bb, B}",
                        "enum": ["C", "C#", "Db", "D", "D#", "Eb", "E", "F", "F#", "Gb", "G", "G#", "Ab", "A", "A#", "Bb", "B"]
                    },
                    "mode": {
                        "description": "Mode: {major, minor, null}",
                        "enum": ["major", "minor", null]
                    }
                }
            }
        },
        "tempos": {
            "description": "Tempos (only effective when `is_symbolic_timing` is true)",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "time": {
                        "description": "Event time",
                        "type": "number"
                    },
                    "tempo": {
                        "description": "Tempo in bpm (beats per minute)",
                        "type": "number"
                    }
                }
            }
        },
        "downbeats": {
            "description": "Downbeat positions",
            "type": ["array", "null"],
            "items": {
                "description": "Downbeat time",
                "type": "number"
            }
        },
        "lyrics": {
            "description": "Global lyrics",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "time": {
                        "description": "Event time",
                        "type": "number"
                    },
                    "lyric": {
                        "description": "Content of lyric",
                        "type": "string"
                    }
                }
            }
        },
        "annotations": {
            "description": "Global annotations",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "time": {
                        "description": "Event time",
                        "type": "number"
                    },
                    "annotation": {
                        "description": "Content of annotation"
                    }
                }
            }
        },
        "tracks": {
            "description": "Tracks",
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Name of track",
                        "type": ["string", "null"]
                    },
                    "program": {
                        "description": "# Program number (according to General MIDI specification)",
                        "type": "number"
                    },
                    "is_drum": {
                        "description": "A boolean indicator that indicates whether it is a percussion track",
                        "type": "boolean"
                    },
                    "notes": {
                        "description": "Notes",
                        "type": ["array", "null"],
                        "items": {
                            "type": "object",
                            "properties": {
                                "start": {
                                    "description": "Start time",
                                    "type": "number"
                                },
                                "end": {
                                    "description": "End time",
                                    "type": "number"
                                },
                                "pitch": {
                                    "description": "Note pitch",
                                    "type": "integer"
                                },
                                "velocity": {
                                    "description": "Note velocity",
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "lyrics": {
                        "description": "Track-specific lyrics",
                        "type": ["array", "null"],
                        "items": {
                            "type": "object",
                            "properties": {
                                "time": {
                                    "description": "Event time",
                                    "type": "number"
                                },
                                "lyric": {
                                    "description": "Content of lyric",
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "annotations": {
                        "description": "Track-specific annotations",
                        "type": "array",
                        "items": {
                            "type": ["object", "null"],
                            "properties": {
                                "time": {
                                    "description": "Event time",
                                    "type": "number"
                                },
                                "annotation": {
                                    "description": "Content of annotation"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== AvatarWorld/muspy/muspy/io/schemas/example.json
{
	"meta": {
		"version": "0.0",
		"song": {
			"title": "FÃ¼r Elise",
			"artist": "Ludwig van Beethoven",
			"composers": [
				"Ludwig van Beethoven"
			]
		},
		"source": {
			"collection": "collection",
			"filename": "example.yaml",
			"format": null,
			"id": "0"
		}
	},
	"timing": {
		"is_symbolic_timing": true,
		"beat_resolution": 4
	},
	"time_signatures": [
		{
			"time": 0,
			"numerator": 3,
			"denominator": 8
		}
	],
	"key_signatures": [
		{
			"time": 0,
			"root": "A",
			"mode": "minor"
		}
	],
	"tempos": [
		{
			"time": 0,
			"tempo": 120
		}
	],
	"downbeats": [
		4,
		16
	],
	"lyrics": [
		{
			"time": 0,
			"lyric": "nothing but a lyric"
		}
	],
	"annotations": [
		{
			"time": 0,
			"annotation": "nothing but an annotation"
		}
	],
	"tracks": [
		{
			"name": "melody",
			"program": 0,
			"is_drum": false,
			"notes": [
				{
					"start": 0,
					"end": 2,
					"pitch": 76,
					"velocity": 127
				},
				{
					"start": 2,
					"end": 4,
					"pitch": 75,
					"velocity": 127
				},
				{
					"start": 4,
					"end": 6,
					"pitch": 76,
					"velocity": 127
				},
				{
					"start": 6,
					"end": 8,
					"pitch": 75,
					"velocity": 127
				},
				{
					"start": 8,
					"end": 10,
					"pitch": 76,
					"velocity": 127
				},
				{
					"start": 10,
					"end": 12,
					"pitch": 71,
					"velocity": 127
				},
				{
					"start": 12,
					"end": 14,
					"pitch": 74,
					"velocity": 127
				},
				{
					"start": 14,
					"end": 16,
					"pitch": 72,
					"velocity": 127
				},
				{
					"start": 16,
					"end": 18,
					"pitch": 69,
					"velocity": 127
				}
			],
			"lyrics": [
				{
					"time": 0,
					"lyric": "nothing but a lyric"
				}
			],
			"annotations": [
				{
					"time": 0,
					"annotation": "nothing but an annotation"
				}
			]
		}
	]
}
